language: ruby
sudo: false
dist: trusty
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
  - rbx-2
  - jruby-head
before_install:
  - gem update bundler
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-18mode
    - rvm: jruby-head
