language: ruby
dist: xenial
rvm:
  - 2.3.3
  - 2.4.0
  - "2.5"
  - "2.6"
  - "2.7"
  - jruby-9.1.5.0
  - jruby-head
before_install:
  - gem update bundler
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: "2.7"
